sudo: required
dist: trusty
language: node_js
node_js:
  - '8.12.0'

before_script:
- npm install -g @vue/cli
- npm install --save-dev vue-gh-pages
- npm run build
- node ./node_modules/vue-gh-pages/index.js -b gh-pages
